### ISSUE TITLE
Warnings For Runtime

### ISSUE THREAD

**Issue by samphomsopha** [thetvdb/metadata.tvshows.thetvdb.com.v4.python#3] opened 2022-01-21 00:38 UTC
There were a few warnings that popped up in the log:
```
2022-01-15 17:52:46.173 T:2224     INFO <general>: initializing python engine.
2022-01-15 17:52:46.361 T:2224     INFO <general>: CPythonInvoker(115, `C:\Users\Darren\AppData\Roaming\Kodi\addons\metadata.tvshows.thetvdb.com.v4.python\thetvdb.py):` script successfully run
2022-01-15 17:52:46.439 T:2224     INFO <general>: Python interpreter stopped
2022-01-15 17:52:47.471 T:7124  WARNING <general>: CVideoInfoTag::GetDurationFromMinuteString <runtime> should be in minutes. Interpreting '0' as 0 minutes
```

But it seemed to deal with them correctly in dealing with perhaps the wrong format for the runtime. As Karellen says, not a major issue but a minor tweak perhaps.

I did also come across one item (the TV show versions of Stig Larsen's Millennium films) which scraped on the old scraper but seems to have vanished from the new database. Those threw up a 404 error in the GUI and the log. Again it dealt with it correctly, but maybe worth noting.
Log snippet of that is at https://paste.kodi.tv/abafemivev

**Comment by romanvm** [comment] 2022-01-30 13:03
Regarding "[TV show versions of Stig Larsen's Millennium films](https://www.themoviedb.org/tv/80855-millenium/season/1)", they are not on TheTVDB.

**Comment by romanvm** [comment] 2022-01-30 13:26
And warnings can be safely ignored. I have added support for episodes runtime information but it some cases those warning seems to be logged with no apparent reason.

**Comment by romanvm** [comment] 2022-02-01 21:04
I'm closing this because all items have been addressed. The scraper won't throw errors on missing translations and regarding the warnings check my post above.

**Closed by romanvm** 2022-02-01 21:04 UTC
Labels: bug

**Comment by KarellenX** [comment] 2022-02-01 21:48
>The scraper won't throw errors on missing translations 

Is there any clue to show that information is missing from the scraper site. I would hate to think how much time I waste trying to find fault with the scraper and Kodi when the problem is at the scraper site. As I mentioned once before, those warnings were helpful.

**Comment by romanvm** [comment] 2022-02-02 13:58
The scraper now writes warnings to the Kodi log instead of throwing errors to the user.
